package core_http_server

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	core_config "github.com/r0mbeg/TramCast/backend/internal/core/config"
)

func TestHealthAndAccessLog(t *testing.T) {
	var logs bytes.Buffer
	s := New(testConfig(), slog.New(slog.NewJSONHandler(&logs, nil)), func(context.Context) error {
		t.Fatal("health check must not access the database")
		return nil
	})
	request := httptest.NewRequest(http.MethodGet, "/healthz?token=query-secret", strings.NewReader("body-secret"))
	request.Header.Set("Authorization", "Bearer header-secret")
	request.Header.Set("X-Request-ID", "client-supplied-secret")
	response := httptest.NewRecorder()
	s.Router().ServeHTTP(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", response.Code)
	}
	id := response.Header().Get("X-Request-ID")
	if id == "" || id == "client-supplied-secret" {
		t.Fatalf("request ID was not generated by the server: %q", id)
	}
	var entry map[string]any
	if err := json.Unmarshal(logs.Bytes(), &entry); err != nil {
		t.Fatal(err)
	}
	if entry["request_id"] != id || entry["path"] != "/healthz" || entry["method"] != "GET" || entry["status"] != float64(200) {
		t.Fatalf("unexpected access log: %s", logs.String())
	}
	for _, secret := range []string{"query-secret", "body-secret", "header-secret", "client-supplied-secret"} {
		if strings.Contains(logs.String(), secret) {
			t.Errorf("access log contains %q", secret)
		}
	}
}

func TestReadiness(t *testing.T) {
	for _, test := range []struct {
		name   string
		ping   func(context.Context) error
		status int
	}{
		{name: "available", ping: func(context.Context) error { return nil }, status: http.StatusOK},
		{name: "unavailable", ping: func(context.Context) error { return errors.New("database-password-secret") }, status: http.StatusServiceUnavailable},
		{name: "probe timeout", ping: func(ctx context.Context) error { <-ctx.Done(); return ctx.Err() }, status: http.StatusServiceUnavailable},
	} {
		t.Run(test.name, func(t *testing.T) {
			var logs bytes.Buffer
			cfg := testConfig()
			cfg.ProbeTimeout = 10 * time.Millisecond
			s := New(cfg, slog.New(slog.NewJSONHandler(&logs, nil)), test.ping)
			response := httptest.NewRecorder()
			s.Router().ServeHTTP(response, httptest.NewRequest(http.MethodGet, "/readyz", nil))
			if response.Code != test.status {
				t.Fatalf("status = %d, want %d", response.Code, test.status)
			}
			if strings.Contains(response.Body.String()+logs.String(), "database-password-secret") {
				t.Fatal("readiness leaked the database error")
			}
		})
	}
}

func TestReadinessPropagatesRequestCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	s := New(testConfig(), quietLogger(), func(ctx context.Context) error {
		if !errors.Is(ctx.Err(), context.Canceled) {
			t.Errorf("ping context error = %v, want cancellation", ctx.Err())
		}
		return ctx.Err()
	})
	response := httptest.NewRecorder()
	s.Router().ServeHTTP(response, httptest.NewRequest(http.MethodGet, "/readyz", nil).WithContext(ctx))
	if response.Code != http.StatusServiceUnavailable {
		t.Fatalf("status = %d, want 503", response.Code)
	}
}

func TestPanicRecoveryDoesNotExposePanicValue(t *testing.T) {
	var logs bytes.Buffer
	s := New(testConfig(), slog.New(slog.NewJSONHandler(&logs, nil)), func(context.Context) error { return nil })
	s.Router().GET("/panic", func(*gin.Context) { panic("panic-password-secret") })
	response := httptest.NewRecorder()
	s.Router().ServeHTTP(response, httptest.NewRequest(http.MethodGet, "/panic", nil))
	if response.Code != http.StatusInternalServerError || response.Body.String() != `{"error":"internal_server_error"}` {
		t.Fatalf("unexpected panic response: %d %s", response.Code, response.Body.String())
	}
	if strings.Contains(response.Body.String()+logs.String(), "panic-password-secret") {
		t.Fatal("panic value leaked")
	}
	if !strings.Contains(logs.String(), `"stack":`) || !strings.Contains(logs.String(), `"status":500`) {
		t.Fatalf("missing recovery or access log: %s", logs.String())
	}
}

func TestInternalErrorIsLoggedButNotExposed(t *testing.T) {
	var logs bytes.Buffer
	s := New(testConfig(), slog.New(slog.NewJSONHandler(&logs, nil)), func(context.Context) error { return nil })
	s.Router().GET("/fail", func(c *gin.Context) {
		WriteInternalError(c, errors.New("query failed: internal-detail-secret"))
	})
	response := httptest.NewRecorder()
	s.Router().ServeHTTP(response, httptest.NewRequest(http.MethodGet, "/fail", nil))

	if response.Code != http.StatusInternalServerError || response.Body.String() != `{"error":"internal_server_error"}` {
		t.Fatalf("unexpected response: %d %s", response.Code, response.Body.String())
	}
	var entry map[string]any
	if err := json.Unmarshal(logs.Bytes(), &entry); err != nil {
		t.Fatal(err)
	}
	if entry["level"] != "ERROR" || !strings.Contains(fmt.Sprint(entry["error"]), "internal-detail-secret") {
		t.Fatalf("access log must keep the internal error at ERROR level: %s", logs.String())
	}
}

func TestProbesAnswerHEAD(t *testing.T) {
	for _, tt := range []struct {
		name, target string
		ping         func(context.Context) error
		status       int
	}{
		{"health", "/healthz", func(context.Context) error { return nil }, http.StatusOK},
		{"ready", "/readyz", func(context.Context) error { return nil }, http.StatusOK},
		{"not ready", "/readyz", func(context.Context) error { return errors.New("database down") }, http.StatusServiceUnavailable},
	} {
		t.Run(tt.name, func(t *testing.T) {
			s := New(testConfig(), quietLogger(), tt.ping)
			// A fallback that would answer 200 proves HEAD does not reach NoRoute.
			s.Router().NoRoute(func(c *gin.Context) { c.String(http.StatusOK, "frontend page") })
			response := httptest.NewRecorder()
			s.Router().ServeHTTP(response, httptest.NewRequest(http.MethodHead, tt.target, nil))
			if response.Code != tt.status || !strings.HasPrefix(response.Header().Get("Content-Type"), "application/json") {
				t.Fatalf("HEAD %s = %d %q, want %d JSON", tt.target, response.Code, response.Header().Get("Content-Type"), tt.status)
			}
		})
	}
}

func TestUnknownRouteReturnsJSONNotFound(t *testing.T) {
	s := New(testConfig(), quietLogger(), func(context.Context) error { return nil })
	response := httptest.NewRecorder()
	s.Router().ServeHTTP(response, httptest.NewRequest(http.MethodGet, "/missing", nil))
	if response.Code != http.StatusNotFound || response.Body.String() != `{"error":"not_found"}` {
		t.Fatalf("unexpected response: %d %s", response.Code, response.Body.String())
	}
}

func TestRunReturnsBindError(t *testing.T) {
	listener := listen(t)
	cfg := testConfig()
	cfg.Addr = listener.Addr().String()
	err := New(cfg, quietLogger(), func(context.Context) error { return nil }).Run(context.Background())
	var networkErr *net.OpError
	if !errors.As(err, &networkErr) || networkErr.Op != "listen" {
		t.Fatalf("error = %v, want listen error", err)
	}
}

func TestShutdownLetsActiveRequestFinish(t *testing.T) {
	listener := &closeNotifier{Listener: listen(t), closed: make(chan struct{})}
	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)
	s := New(testConfig(), quietLogger(), func(context.Context) error { return nil })
	started := make(chan context.Context, 1)
	release := make(chan struct{})
	var releaseOnce sync.Once
	releaseHandler := func() { releaseOnce.Do(func() { close(release) }) }
	t.Cleanup(releaseHandler)
	s.Router().GET("/slow", func(c *gin.Context) {
		started <- c.Request.Context()
		<-release
		c.JSON(http.StatusOK, gin.H{"status": "finished"})
	})
	done := make(chan error, 1)
	go func() { done <- s.serve(ctx, listener) }()
	requestDone := getAsync(listener.Addr().String() + "/slow")
	requestCtx := receive(t, started)
	cancel()
	receive(t, listener.closed)
	if err := requestCtx.Err(); err != nil {
		t.Fatalf("active request was cancelled before the shutdown deadline: %v", err)
	}
	releaseHandler()
	result := receive(t, requestDone)
	if result.err != nil || result.status != http.StatusOK || result.body != `{"status":"finished"}` {
		t.Fatalf("active request did not finish: %+v", result)
	}
	if err := receive(t, done); err != nil {
		t.Fatalf("graceful shutdown: %v", err)
	}
}

func TestShutdownDeadlineClosesAndCancelsActiveRequest(t *testing.T) {
	listener := listen(t)
	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)
	cfg := testConfig()
	cfg.ShutdownTimeout = 10 * time.Millisecond
	s := New(cfg, quietLogger(), func(context.Context) error { return nil })
	started := make(chan struct{})
	cancelled := make(chan struct{})
	s.Router().GET("/blocked", func(c *gin.Context) {
		close(started)
		<-c.Request.Context().Done()
		close(cancelled)
	})
	done := make(chan error, 1)
	go func() { done <- s.serve(ctx, listener) }()
	requestDone := getAsync(listener.Addr().String() + "/blocked")
	receive(t, started)
	cancel()
	if err := receive(t, done); !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("shutdown error = %v, want deadline exceeded", err)
	}
	receive(t, cancelled)
	receive(t, requestDone)
}

func testConfig() core_config.HTTPConfig {
	return core_config.HTTPConfig{
		Addr:              "127.0.0.1:0",
		ReadHeaderTimeout: time.Second,
		ReadTimeout:       time.Second,
		WriteTimeout:      5 * time.Second,
		IdleTimeout:       time.Second,
		ShutdownTimeout:   time.Second,
		ProbeTimeout:      time.Second,
	}
}

func quietLogger() *slog.Logger {
	return slog.New(slog.NewJSONHandler(io.Discard, nil))
}

func listen(t *testing.T) net.Listener {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = listener.Close() })
	return listener
}

type closeNotifier struct {
	net.Listener
	closed chan struct{}
	once   sync.Once
}

func (l *closeNotifier) Close() error {
	err := l.Listener.Close()
	l.once.Do(func() { close(l.closed) })
	return err
}

type requestResult struct {
	status int
	body   string
	err    error
}

func getAsync(address string) <-chan requestResult {
	result := make(chan requestResult, 1)
	go func() {
		client := &http.Client{Timeout: 5 * time.Second}
		response, err := client.Get("http://" + address)
		if err != nil {
			result <- requestResult{err: err}
			return
		}
		defer response.Body.Close()
		body, err := io.ReadAll(response.Body)
		result <- requestResult{status: response.StatusCode, body: string(body), err: err}
	}()
	return result
}

func receive[T any](t *testing.T, channel <-chan T) T {
	t.Helper()
	select {
	case result := <-channel:
		return result
	case <-time.After(5 * time.Second):
		t.Fatal("timed out waiting for test event")
		var zero T
		return zero
	}
}
