// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package routes_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Route struct {
	ID              int64       `json:"id"`
	RouteNumber     int16       `json:"route_number"`
	Name            pgtype.Text `json:"name"`
	SourceRouteID   pgtype.Text `json:"source_route_id"`
	ForecastEnabled bool        `json:"forecast_enabled"`
}
