// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package routes_sqlc

import (
	"context"
)

type Querier interface {
	// Use only within the replacement transaction after GetRouteForUpdate.
	DeleteRouteStops(ctx context.Context, routeID int64) (int64, error)
	// After this statement, read the existing/new row with GetRouteByNumber.
	EnsureRoute(ctx context.Context, routeNumber int16) (int64, error)
	GetRouteByID(ctx context.Context, routeID int64) (Route, error)
	GetRouteByNumber(ctx context.Context, routeNumber int16) (Route, error)
	GetRouteBySourceID(ctx context.Context, sourceRouteID string) (Route, error)
	// Lock before replacing this route's positions; hold through delete and inserts.
	GetRouteForUpdate(ctx context.Context, routeID int64) (Route, error)
	// In the same transaction, insert the validated full set after DeleteRouteStops.
	// Go verifies one direction_id per pattern_key before replacing any positions.
	InsertRouteStop(ctx context.Context, arg InsertRouteStopParams) error
	// All positions of all routes with stop coordinates, ordered so that the rows
	// of one movement variant are adjacent and follow stop_sequence.
	ListRouteGeometry(ctx context.Context) ([]ListRouteGeometryRow, error)
	ListRoutePatterns(ctx context.Context, routeID int64) ([]ListRoutePatternsRow, error)
	ListRouteStops(ctx context.Context, routeID int64) ([]ListRouteStopsRow, error)
	ListRoutes(ctx context.Context) ([]Route, error)
	SetRouteForecastEnabled(ctx context.Context, arg SetRouteForecastEnabledParams) (int64, error)
	// Missing catalog fields preserve existing values; enabling forecasts is separate.
	UpsertRoute(ctx context.Context, arg UpsertRouteParams) (Route, error)
}

var _ Querier = (*Queries)(nil)
