// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: route_stops.sql

package routes_sqlc

import (
	"context"
)

const deleteRouteStops = `-- name: DeleteRouteStops :execrows
DELETE FROM routes_stops
WHERE route_id = $1
`

// Use only within the replacement transaction after GetRouteForUpdate.
func (q *Queries) DeleteRouteStops(ctx context.Context, routeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRouteStops, routeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRouteStop = `-- name: InsertRouteStop :exec
INSERT INTO routes_stops (route_id, pattern_key, direction_id, stop_sequence, stop_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertRouteStopParams struct {
	RouteID      int64  `json:"route_id"`
	PatternKey   string `json:"pattern_key"`
	DirectionID  int16  `json:"direction_id"`
	StopSequence int32  `json:"stop_sequence"`
	StopID       int64  `json:"stop_id"`
}

// In the same transaction, insert the validated full set after DeleteRouteStops.
// Go verifies one direction_id per pattern_key before replacing any positions.
func (q *Queries) InsertRouteStop(ctx context.Context, arg InsertRouteStopParams) error {
	_, err := q.db.Exec(ctx, insertRouteStop,
		arg.RouteID,
		arg.PatternKey,
		arg.DirectionID,
		arg.StopSequence,
		arg.StopID,
	)
	return err
}

const listRouteGeometry = `-- name: ListRouteGeometry :many
SELECT rs.route_id,
       r.route_number,
       r.forecast_enabled,
       rs.pattern_key,
       rs.direction_id,
       rs.stop_sequence,
       s.latitude,
       s.longitude
FROM routes_stops AS rs
JOIN routes AS r ON r.id = rs.route_id
JOIN stops AS s ON s.id = rs.stop_id
ORDER BY r.route_number, rs.route_id, rs.direction_id, rs.pattern_key, rs.stop_sequence
`

type ListRouteGeometryRow struct {
	RouteID         int64   `json:"route_id"`
	RouteNumber     int16   `json:"route_number"`
	ForecastEnabled bool    `json:"forecast_enabled"`
	PatternKey      string  `json:"pattern_key"`
	DirectionID     int16   `json:"direction_id"`
	StopSequence    int32   `json:"stop_sequence"`
	Latitude        float64 `json:"latitude"`
	Longitude       float64 `json:"longitude"`
}

// All positions of all routes with stop coordinates, ordered so that the rows
// of one movement variant are adjacent and follow stop_sequence.
func (q *Queries) ListRouteGeometry(ctx context.Context) ([]ListRouteGeometryRow, error) {
	rows, err := q.db.Query(ctx, listRouteGeometry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteGeometryRow{}
	for rows.Next() {
		var i ListRouteGeometryRow
		if err := rows.Scan(
			&i.RouteID,
			&i.RouteNumber,
			&i.ForecastEnabled,
			&i.PatternKey,
			&i.DirectionID,
			&i.StopSequence,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutePatterns = `-- name: ListRoutePatterns :many
SELECT pattern_key, direction_id
FROM routes_stops
WHERE route_id = $1
GROUP BY pattern_key, direction_id
ORDER BY direction_id, pattern_key
`

type ListRoutePatternsRow struct {
	PatternKey  string `json:"pattern_key"`
	DirectionID int16  `json:"direction_id"`
}

func (q *Queries) ListRoutePatterns(ctx context.Context, routeID int64) ([]ListRoutePatternsRow, error) {
	rows, err := q.db.Query(ctx, listRoutePatterns, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutePatternsRow{}
	for rows.Next() {
		var i ListRoutePatternsRow
		if err := rows.Scan(&i.PatternKey, &i.DirectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteStops = `-- name: ListRouteStops :many
SELECT rs.route_id,
       rs.pattern_key,
       rs.direction_id,
       rs.stop_sequence,
       s.id AS stop_id,
       s.source_stop_id,
       s.name,
       s.latitude,
       s.longitude
FROM routes_stops AS rs
JOIN stops AS s ON s.id = rs.stop_id
WHERE rs.route_id = $1
ORDER BY rs.direction_id, rs.pattern_key, rs.stop_sequence
`

type ListRouteStopsRow struct {
	RouteID      int64   `json:"route_id"`
	PatternKey   string  `json:"pattern_key"`
	DirectionID  int16   `json:"direction_id"`
	StopSequence int32   `json:"stop_sequence"`
	StopID       int64   `json:"stop_id"`
	SourceStopID string  `json:"source_stop_id"`
	Name         string  `json:"name"`
	Latitude     float64 `json:"latitude"`
	Longitude    float64 `json:"longitude"`
}

func (q *Queries) ListRouteStops(ctx context.Context, routeID int64) ([]ListRouteStopsRow, error) {
	rows, err := q.db.Query(ctx, listRouteStops, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteStopsRow{}
	for rows.Next() {
		var i ListRouteStopsRow
		if err := rows.Scan(
			&i.RouteID,
			&i.PatternKey,
			&i.DirectionID,
			&i.StopSequence,
			&i.StopID,
			&i.SourceStopID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
