// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package routes_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureRoute = `-- name: EnsureRoute :execrows
INSERT INTO routes (route_number)
VALUES ($1)
ON CONFLICT (route_number) DO NOTHING
`

// After this statement, read the existing/new row with GetRouteByNumber.
func (q *Queries) EnsureRoute(ctx context.Context, routeNumber int16) (int64, error) {
	result, err := q.db.Exec(ctx, ensureRoute, routeNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT id, route_number, name, source_route_id, forecast_enabled
FROM routes
WHERE id = $1
`

func (q *Queries) GetRouteByID(ctx context.Context, routeID int64) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByID, routeID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.RouteNumber,
		&i.Name,
		&i.SourceRouteID,
		&i.ForecastEnabled,
	)
	return i, err
}

const getRouteByNumber = `-- name: GetRouteByNumber :one
SELECT id, route_number, name, source_route_id, forecast_enabled
FROM routes
WHERE route_number = $1
`

func (q *Queries) GetRouteByNumber(ctx context.Context, routeNumber int16) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByNumber, routeNumber)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.RouteNumber,
		&i.Name,
		&i.SourceRouteID,
		&i.ForecastEnabled,
	)
	return i, err
}

const getRouteBySourceID = `-- name: GetRouteBySourceID :one
SELECT id, route_number, name, source_route_id, forecast_enabled
FROM routes
WHERE source_route_id = $1::text
`

func (q *Queries) GetRouteBySourceID(ctx context.Context, sourceRouteID string) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteBySourceID, sourceRouteID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.RouteNumber,
		&i.Name,
		&i.SourceRouteID,
		&i.ForecastEnabled,
	)
	return i, err
}

const getRouteForUpdate = `-- name: GetRouteForUpdate :one
SELECT id, route_number, name, source_route_id, forecast_enabled
FROM routes
WHERE id = $1
FOR UPDATE
`

// Lock before replacing this route's positions; hold through delete and inserts.
func (q *Queries) GetRouteForUpdate(ctx context.Context, routeID int64) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteForUpdate, routeID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.RouteNumber,
		&i.Name,
		&i.SourceRouteID,
		&i.ForecastEnabled,
	)
	return i, err
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, route_number, name, source_route_id, forecast_enabled
FROM routes
ORDER BY route_number, id
`

func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.RouteNumber,
			&i.Name,
			&i.SourceRouteID,
			&i.ForecastEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRouteForecastEnabled = `-- name: SetRouteForecastEnabled :execrows
UPDATE routes
SET forecast_enabled = $1
WHERE id = $2
`

type SetRouteForecastEnabledParams struct {
	ForecastEnabled bool  `json:"forecast_enabled"`
	RouteID         int64 `json:"route_id"`
}

func (q *Queries) SetRouteForecastEnabled(ctx context.Context, arg SetRouteForecastEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRouteForecastEnabled, arg.ForecastEnabled, arg.RouteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRoute = `-- name: UpsertRoute :one
INSERT INTO routes (route_number, name, source_route_id)
VALUES (
    $1,
    $2::text,
    $3::text
)
ON CONFLICT (route_number) DO UPDATE
SET name = COALESCE(EXCLUDED.name, routes.name),
    source_route_id = COALESCE(EXCLUDED.source_route_id, routes.source_route_id)
RETURNING id, route_number, name, source_route_id, forecast_enabled
`

type UpsertRouteParams struct {
	RouteNumber   int16       `json:"route_number"`
	Name          pgtype.Text `json:"name"`
	SourceRouteID pgtype.Text `json:"source_route_id"`
}

// Missing catalog fields preserve existing values; enabling forecasts is separate.
func (q *Queries) UpsertRoute(ctx context.Context, arg UpsertRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, upsertRoute, arg.RouteNumber, arg.Name, arg.SourceRouteID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.RouteNumber,
		&i.Name,
		&i.SourceRouteID,
		&i.ForecastEnabled,
	)
	return i, err
}
