// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalog_sqlc

import (
	"context"
)

const deleteUnusedStopsNotInCatalog = `-- name: DeleteUnusedStopsNotInCatalog :execrows
DELETE FROM stops AS s
WHERE NOT (s.source_stop_id = ANY ($1::text[]))
  AND NOT EXISTS (
      SELECT 1
      FROM routes_stops AS rs
      WHERE rs.stop_id = s.id
  )
`

// Run after positions are replaced: removes stops absent from the imported
// sources that no position references any more.
func (q *Queries) DeleteUnusedStopsNotInCatalog(ctx context.Context, sourceStopIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedStopsNotInCatalog, sourceStopIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockCatalogImport = `-- name: LockCatalogImport :exec
SELECT pg_advisory_xact_lock(hashtext('tramcast.catalog_import'))
`

// Serializes catalog imports; the lock is released at commit or rollback.
func (q *Queries) LockCatalogImport(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCatalogImport)
	return err
}
