// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalog_sqlc

import (
	"context"
)

const catalogHasData = `-- name: CatalogHasData :one
SELECT EXISTS (
    SELECT 1 FROM routes
    UNION ALL
    SELECT 1 FROM stops
    UNION ALL
    SELECT 1 FROM routes_stops
) AS has_data
`

// Check after LockCatalogImport in a separate READ COMMITTED statement, so
// an import that committed while the lock was awaited is visible.
func (q *Queries) CatalogHasData(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, catalogHasData)
	var has_data bool
	err := row.Scan(&has_data)
	return has_data, err
}

const deleteUnusedStopsNotInCatalog = `-- name: DeleteUnusedStopsNotInCatalog :execrows
DELETE FROM stops AS s
WHERE NOT (s.source_stop_id = ANY ($1::text[]))
  AND NOT EXISTS (
      SELECT 1
      FROM routes_stops AS rs
      WHERE rs.stop_id = s.id
  )
`

// Run after positions are replaced: removes stops absent from the imported
// sources that no position references any more.
func (q *Queries) DeleteUnusedStopsNotInCatalog(ctx context.Context, sourceStopIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedStopsNotInCatalog, sourceStopIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockCatalogImport = `-- name: LockCatalogImport :exec
SELECT pg_advisory_xact_lock(hashtext('tramcast.catalog_import'))
`

// Serializes catalog imports; the lock is released at commit or rollback.
func (q *Queries) LockCatalogImport(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCatalogImport)
	return err
}
