// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalog_sqlc

import (
	"context"
)

type Querier interface {
	// Run after positions are replaced: removes stops absent from the imported
	// sources that no position references any more.
	DeleteUnusedStopsNotInCatalog(ctx context.Context, sourceStopIds []string) (int64, error)
	// Serializes catalog imports; the lock is released at commit or rollback.
	LockCatalogImport(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
