// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package forecasts_sqlc

import (
	"context"
)

// iteratorForCopyValidationPredictions implements pgx.CopyFromSource.
type iteratorForCopyValidationPredictions struct {
	rows                 []CopyValidationPredictionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyValidationPredictions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyValidationPredictions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ForecastVersionID,
		r.rows[0].RouteID,
		r.rows[0].Date,
		r.rows[0].Hour,
		r.rows[0].Boardings,
	}, nil
}

func (r iteratorForCopyValidationPredictions) Err() error {
	return nil
}

// Copy the verified full route/version horizon using Queries.WithTx(tx).
// First lock the owned running job and check attempt_count and its valid lease;
// then copy every point and mark success in this same transaction. Any error,
// missing ownership, or an unexpected copy count requires rollback of the batch.
// Validate point metadata and the exact grid before the transaction. Published
// values are immutable: there is deliberately no UPDATE or ON CONFLICT clause.
func (q *Queries) CopyValidationPredictions(ctx context.Context, arg []CopyValidationPredictionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"validation_predictions"}, []string{"forecast_version_id", "route_id", "date", "hour", "boardings"}, &iteratorForCopyValidationPredictions{rows: arg})
}
