// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package forecasts_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPredictionJob = `-- name: ClaimNextPredictionJob :one
WITH candidate AS MATERIALIZED (
    SELECT id
    FROM prediction_jobs
    WHERE status = 'queued'
        AND run_after <= clock_timestamp()
        AND attempt_count < $2::integer
        AND $1::integer > 0
    ORDER BY run_after, created_at, id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE prediction_jobs AS job
SET status = 'running',
    attempt_count = job.attempt_count + 1,
    started_at = clock_timestamp(),
    lease_until = clock_timestamp() + $1::integer * INTERVAL '1 second',
    finished_at = NULL
FROM candidate
WHERE job.id = candidate.id
RETURNING job.id, job.forecast_version_id, job.route_id, job.status, job.attempt_count,
    job.run_after, job.lease_until, job.created_at, job.started_at, job.finished_at,
    job.last_error_code, job.last_error_message
`

type ClaimNextPredictionJobParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	MaxAttempts  int32 `json:"max_attempts"`
}

// Commit the short claim transaction BEFORE starting the RPC. The returned
// attempt_count is the ownership token used by every worker mutation.
func (q *Queries) ClaimNextPredictionJob(ctx context.Context, arg ClaimNextPredictionJobParams) (PredictionJob, error) {
	row := q.db.QueryRow(ctx, claimNextPredictionJob, arg.LeaseSeconds, arg.MaxAttempts)
	var i PredictionJob
	err := row.Scan(
		&i.ID,
		&i.ForecastVersionID,
		&i.RouteID,
		&i.Status,
		&i.AttemptCount,
		&i.RunAfter,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const completePredictionJob = `-- name: CompletePredictionJob :execrows
UPDATE prediction_jobs
SET status = 'succeeded',
    finished_at = clock_timestamp(),
    lease_until = NULL,
    last_error_code = NULL,
    last_error_message = NULL
WHERE id = $1::uuid
    AND status = 'running'
    AND attempt_count = $2::integer
`

type CompletePredictionJobParams struct {
	ID            pgtype.UUID `json:"id"`
	AttemptNumber int32       `json:"attempt_number"`
}

// ONLY after LockPredictionJobForPublication and a successful full COPY in the
// same transaction. Require exactly one affected row, otherwise ROLLBACK.
// Do not recheck expiry here: the row lock has protected ownership throughout
// publication, even if the lease elapsed while copying the verified points.
func (q *Queries) CompletePredictionJob(ctx context.Context, arg CompletePredictionJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completePredictionJob, arg.ID, arg.AttemptNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingPredictionJobs = `-- name: CountPendingPredictionJobs :one
SELECT count(*) FROM prediction_jobs WHERE status IN ('queued', 'running')
`

// Admission capacity covers both waiting and running jobs, including retries.
func (q *Queries) CountPendingPredictionJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingPredictionJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPredictionJob = `-- name: CreatePredictionJob :one
INSERT INTO prediction_jobs (id, forecast_version_id, route_id)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::bigint
)
ON CONFLICT (forecast_version_id, route_id) DO NOTHING
RETURNING id, forecast_version_id, route_id, status, attempt_count, run_after,
    lease_until, created_at, started_at, finished_at, last_error_code, last_error_message
`

type CreatePredictionJobParams struct {
	ID                pgtype.UUID `json:"id"`
	ForecastVersionID pgtype.UUID `json:"forecast_version_id"`
	RouteID           int64       `json:"route_id"`
}

// Use only in the admission transaction. On conflict, no row is returned:
// issue GetPredictionJobByRouteAndVersion as a NEW statement (fresh snapshot).
// Do not combine INSERT DO NOTHING and fallback SELECT in one CTE snapshot.
func (q *Queries) CreatePredictionJob(ctx context.Context, arg CreatePredictionJobParams) (PredictionJob, error) {
	row := q.db.QueryRow(ctx, createPredictionJob, arg.ID, arg.ForecastVersionID, arg.RouteID)
	var i PredictionJob
	err := row.Scan(
		&i.ID,
		&i.ForecastVersionID,
		&i.RouteID,
		&i.Status,
		&i.AttemptCount,
		&i.RunAfter,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const failExhaustedQueuedPredictionJobs = `-- name: FailExhaustedQueuedPredictionJobs :many
WITH exhausted_jobs AS MATERIALIZED (
    SELECT id
    FROM prediction_jobs
    WHERE status = 'queued'
        AND attempt_count >= $1::integer
        AND $1::integer > 0
    ORDER BY created_at, id
    LIMIT $2::integer
    FOR UPDATE SKIP LOCKED
)
UPDATE prediction_jobs AS job
SET status = 'failed',
    finished_at = clock_timestamp(),
    lease_until = NULL,
    last_error_code = 'attempt_limit_exceeded',
    last_error_message = 'The configured attempt limit has been reached'
FROM exhausted_jobs
WHERE job.id = exhausted_jobs.id
RETURNING job.id, job.status, job.attempt_count
`

type FailExhaustedQueuedPredictionJobsParams struct {
	MaxAttempts int32 `json:"max_attempts"`
	BatchSize   int32 `json:"batch_size"`
}

type FailExhaustedQueuedPredictionJobsRow struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	AttemptCount int32       `json:"attempt_count"`
}

// Run during worker maintenance, including after lowering max_attempts in
// configuration, so exhausted queued jobs cannot occupy capacity forever.
func (q *Queries) FailExhaustedQueuedPredictionJobs(ctx context.Context, arg FailExhaustedQueuedPredictionJobsParams) ([]FailExhaustedQueuedPredictionJobsRow, error) {
	rows, err := q.db.Query(ctx, failExhaustedQueuedPredictionJobs, arg.MaxAttempts, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailExhaustedQueuedPredictionJobsRow{}
	for rows.Next() {
		var i FailExhaustedQueuedPredictionJobsRow
		if err := rows.Scan(&i.ID, &i.Status, &i.AttemptCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishPredictionJobWithError = `-- name: FinishPredictionJobWithError :one
WITH locked_job AS MATERIALIZED (
    SELECT id, status, attempt_count, lease_until
    FROM prediction_jobs
    WHERE id = $7::uuid
    FOR UPDATE
)
UPDATE prediction_jobs AS job
SET status = CASE
        WHEN $1::boolean AND locked_job.attempt_count < $2::integer
        THEN 'queued' ELSE 'failed' END,
    run_after = CASE
        WHEN $1::boolean AND locked_job.attempt_count < $2::integer
        THEN clock_timestamp() + $3::integer * INTERVAL '1 second'
        ELSE job.run_after END,
    finished_at = CASE
        WHEN $1::boolean AND locked_job.attempt_count < $2::integer
        THEN NULL ELSE clock_timestamp() END,
    lease_until = NULL,
    last_error_code = $4::text,
    last_error_message = $5::text
FROM locked_job
WHERE job.id = locked_job.id
    AND locked_job.status = 'running'
    AND locked_job.attempt_count = $6::integer
    AND locked_job.lease_until > clock_timestamp()
    AND $2::integer > 0
    AND $3::integer >= 0
RETURNING job.id, job.forecast_version_id, job.route_id, job.status, job.attempt_count,
    job.run_after, job.lease_until, job.created_at, job.started_at, job.finished_at,
    job.last_error_code, job.last_error_message
`

type FinishPredictionJobWithErrorParams struct {
	Retryable         bool        `json:"retryable"`
	MaxAttempts       int32       `json:"max_attempts"`
	RetryDelaySeconds int32       `json:"retry_delay_seconds"`
	ErrorCode         string      `json:"error_code"`
	ErrorMessage      string      `json:"error_message"`
	AttemptNumber     int32       `json:"attempt_number"`
	ID                pgtype.UUID `json:"id"`
}

// A stale worker cannot requeue/fail a newer attempt or revive an expired lease.
// retryable=false is terminal. A retry also requires remaining attempts.
func (q *Queries) FinishPredictionJobWithError(ctx context.Context, arg FinishPredictionJobWithErrorParams) (PredictionJob, error) {
	row := q.db.QueryRow(ctx, finishPredictionJobWithError,
		arg.Retryable,
		arg.MaxAttempts,
		arg.RetryDelaySeconds,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.AttemptNumber,
		arg.ID,
	)
	var i PredictionJob
	err := row.Scan(
		&i.ID,
		&i.ForecastVersionID,
		&i.RouteID,
		&i.Status,
		&i.AttemptCount,
		&i.RunAfter,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const getPredictionJob = `-- name: GetPredictionJob :one
SELECT id, forecast_version_id, route_id, status, attempt_count, run_after,
    lease_until, created_at, started_at, finished_at, last_error_code, last_error_message
FROM prediction_jobs
WHERE id = $1::uuid
`

func (q *Queries) GetPredictionJob(ctx context.Context, id pgtype.UUID) (PredictionJob, error) {
	row := q.db.QueryRow(ctx, getPredictionJob, id)
	var i PredictionJob
	err := row.Scan(
		&i.ID,
		&i.ForecastVersionID,
		&i.RouteID,
		&i.Status,
		&i.AttemptCount,
		&i.RunAfter,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const getPredictionJobByRouteAndVersion = `-- name: GetPredictionJobByRouteAndVersion :one
SELECT id, forecast_version_id, route_id, status, attempt_count, run_after,
    lease_until, created_at, started_at, finished_at, last_error_code, last_error_message
FROM prediction_jobs
WHERE forecast_version_id = $1::uuid
    AND route_id = $2::bigint
`

type GetPredictionJobByRouteAndVersionParams struct {
	ForecastVersionID pgtype.UUID `json:"forecast_version_id"`
	RouteID           int64       `json:"route_id"`
}

func (q *Queries) GetPredictionJobByRouteAndVersion(ctx context.Context, arg GetPredictionJobByRouteAndVersionParams) (PredictionJob, error) {
	row := q.db.QueryRow(ctx, getPredictionJobByRouteAndVersion, arg.ForecastVersionID, arg.RouteID)
	var i PredictionJob
	err := row.Scan(
		&i.ID,
		&i.ForecastVersionID,
		&i.RouteID,
		&i.Status,
		&i.AttemptCount,
		&i.RunAfter,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const lockPredictionJobAdmission = `-- name: LockPredictionJobAdmission :exec
LOCK TABLE prediction_jobs IN SHARE ROW EXCLUSIVE MODE
`

// Short READ COMMITTED transaction, BEFORE taking any row locks:
// lock -> GetPredictionJobByRouteAndVersion -> CountPendingPredictionJobs
// -> CreatePredictionJob if below capacity -> commit. Reuse existing jobs even
// at capacity. The lock serializes admissions; never keep it during an RPC.
func (q *Queries) LockPredictionJobAdmission(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockPredictionJobAdmission)
	return err
}

const lockPredictionJobForPublication = `-- name: LockPredictionJobForPublication :one
WITH locked_job AS MATERIALIZED (
    SELECT id, forecast_version_id, route_id, status, attempt_count, run_after,
        lease_until, created_at, started_at, finished_at, last_error_code, last_error_message
    FROM prediction_jobs
    WHERE id = $2::uuid
    FOR UPDATE
)
SELECT id, forecast_version_id, route_id, status, attempt_count, run_after,
    lease_until, created_at, started_at, finished_at, last_error_code, last_error_message
FROM locked_job
WHERE status = 'running'
    AND attempt_count = $1::integer
    AND lease_until > clock_timestamp()
`

type LockPredictionJobForPublicationParams struct {
	AttemptNumber int32       `json:"attempt_number"`
	ID            pgtype.UUID `json:"id"`
}

type LockPredictionJobForPublicationRow struct {
	ID                pgtype.UUID        `json:"id"`
	ForecastVersionID pgtype.UUID        `json:"forecast_version_id"`
	RouteID           int64              `json:"route_id"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	RunAfter          pgtype.Timestamptz `json:"run_after"`
	LeaseUntil        pgtype.Timestamptz `json:"lease_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	LastErrorCode     pgtype.Text        `json:"last_error_code"`
	LastErrorMessage  pgtype.Text        `json:"last_error_message"`
}

// Must run in the SAME transaction as CopyValidationPredictions and
// CompletePredictionJob. No row means ownership was lost: ROLLBACK.
// Check the exact response grid and metadata before opening the transaction.
func (q *Queries) LockPredictionJobForPublication(ctx context.Context, arg LockPredictionJobForPublicationParams) (LockPredictionJobForPublicationRow, error) {
	row := q.db.QueryRow(ctx, lockPredictionJobForPublication, arg.AttemptNumber, arg.ID)
	var i LockPredictionJobForPublicationRow
	err := row.Scan(
		&i.ID,
		&i.ForecastVersionID,
		&i.RouteID,
		&i.Status,
		&i.AttemptCount,
		&i.RunAfter,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const recoverExpiredPredictionJobs = `-- name: RecoverExpiredPredictionJobs :many
WITH expired_jobs AS MATERIALIZED (
    SELECT id
    FROM prediction_jobs
    WHERE status = 'running'
        AND lease_until <= clock_timestamp()
        AND $1::integer > 0
        AND $2::integer >= 0
    ORDER BY lease_until, id
    LIMIT $3::integer
    FOR UPDATE SKIP LOCKED
)
UPDATE prediction_jobs AS job
SET status = CASE WHEN job.attempt_count < $1::integer
        THEN 'queued' ELSE 'failed' END,
    run_after = CASE WHEN job.attempt_count < $1::integer
        THEN clock_timestamp() + $2::integer * INTERVAL '1 second'
        ELSE job.run_after END,
    finished_at = CASE WHEN job.attempt_count < $1::integer
        THEN NULL ELSE clock_timestamp() END,
    lease_until = NULL,
    last_error_code = 'lease_expired',
    last_error_message = 'The worker lease expired before completion'
FROM expired_jobs
WHERE job.id = expired_jobs.id
RETURNING job.id, job.status, job.attempt_count
`

type RecoverExpiredPredictionJobsParams struct {
	MaxAttempts       int32 `json:"max_attempts"`
	RetryDelaySeconds int32 `json:"retry_delay_seconds"`
	BatchSize         int32 `json:"batch_size"`
}

type RecoverExpiredPredictionJobsRow struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	AttemptCount int32       `json:"attempt_count"`
}

// Bounded recovery; SKIP LOCKED leaves jobs being published/renewed alone.
// The next claim, not recovery, increments attempt_count.
func (q *Queries) RecoverExpiredPredictionJobs(ctx context.Context, arg RecoverExpiredPredictionJobsParams) ([]RecoverExpiredPredictionJobsRow, error) {
	rows, err := q.db.Query(ctx, recoverExpiredPredictionJobs, arg.MaxAttempts, arg.RetryDelaySeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoverExpiredPredictionJobsRow{}
	for rows.Next() {
		var i RecoverExpiredPredictionJobsRow
		if err := rows.Scan(&i.ID, &i.Status, &i.AttemptCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewPredictionJobLease = `-- name: RenewPredictionJobLease :execrows
WITH locked_job AS MATERIALIZED (
    SELECT id, status, attempt_count, lease_until
    FROM prediction_jobs
    WHERE id = $3::uuid
    FOR UPDATE
)
UPDATE prediction_jobs AS job
SET lease_until = GREATEST(
    locked_job.lease_until,
    clock_timestamp() + $1::integer * INTERVAL '1 second'
)
FROM locked_job
WHERE job.id = locked_job.id
    AND locked_job.status = 'running'
    AND locked_job.attempt_count = $2::integer
    AND locked_job.lease_until > clock_timestamp()
    AND $1::integer > 0
`

type RenewPredictionJobLeaseParams struct {
	LeaseSeconds  int32       `json:"lease_seconds"`
	AttemptNumber int32       `json:"attempt_number"`
	ID            pgtype.UUID `json:"id"`
}

// Materialization ensures ownership is checked against the locked row and the
// actual clock AFTER waiting for that lock, not transaction-start time.
// Zero affected rows means ownership was lost (or lease_seconds was invalid).
func (q *Queries) RenewPredictionJobLease(ctx context.Context, arg RenewPredictionJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewPredictionJobLease, arg.LeaseSeconds, arg.AttemptNumber, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
