// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package forecasts_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ForecastVersion struct {
	ID             pgtype.UUID        `json:"id"`
	ModelVersion   string             `json:"model_version"`
	DatasetVersion string             `json:"dataset_version"`
	HistoryEnd     pgtype.Timestamptz `json:"history_end"`
	ForecastFrom   pgtype.Timestamptz `json:"forecast_from"`
	ForecastTo     pgtype.Timestamptz `json:"forecast_to"`
	Timezone       string             `json:"timezone"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PredictionJob struct {
	ID                pgtype.UUID        `json:"id"`
	ForecastVersionID pgtype.UUID        `json:"forecast_version_id"`
	RouteID           int64              `json:"route_id"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	RunAfter          pgtype.Timestamptz `json:"run_after"`
	LeaseUntil        pgtype.Timestamptz `json:"lease_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	LastErrorCode     pgtype.Text        `json:"last_error_code"`
	LastErrorMessage  pgtype.Text        `json:"last_error_message"`
}

type ValidationPrediction struct {
	ForecastVersionID pgtype.UUID        `json:"forecast_version_id"`
	RouteID           int64              `json:"route_id"`
	Date              pgtype.Date        `json:"date"`
	Hour              int16              `json:"hour"`
	Boardings         int64              `json:"boardings"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
