// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package forecasts_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Call after deactivation in the same transaction. Roll back on any error.
	ActivateForecastVersion(ctx context.Context, id pgtype.UUID) (ForecastVersion, error)
	// Commit the short claim transaction BEFORE starting the RPC. The returned
	// attempt_count is the ownership token used by every worker mutation.
	ClaimNextPredictionJob(ctx context.Context, arg ClaimNextPredictionJobParams) (PredictionJob, error)
	// ONLY after LockPredictionJobForPublication and a successful full COPY in the
	// same transaction. Require exactly one affected row, otherwise ROLLBACK.
	// Do not recheck expiry here: the row lock has protected ownership throughout
	// publication, even if the lease elapsed while copying the verified points.
	CompletePredictionJob(ctx context.Context, arg CompletePredictionJobParams) (int64, error)
	// Copy the verified full route/version horizon using Queries.WithTx(tx).
	// First lock the owned running job and check attempt_count and its valid lease;
	// then copy every point and mark success in this same transaction. Any error,
	// missing ownership, or an unexpected copy count requires rollback of the batch.
	// Validate point metadata and the exact grid before the transaction. Published
	// values are immutable: there is deliberately no UPDATE or ON CONFLICT clause.
	CopyValidationPredictions(ctx context.Context, arg []CopyValidationPredictionsParams) (int64, error)
	// Admission capacity covers both waiting and running jobs, including retries.
	CountPendingPredictionJobs(ctx context.Context) (int64, error)
	// Versions are registered inactive. Metadata is immutable after creation.
	CreateForecastVersion(ctx context.Context, arg CreateForecastVersionParams) (ForecastVersion, error)
	// Use only in the admission transaction. On conflict, no row is returned:
	// issue GetPredictionJobByRouteAndVersion as a NEW statement (fresh snapshot).
	// Do not combine INSERT DO NOTHING and fallback SELECT in one CTE snapshot.
	CreatePredictionJob(ctx context.Context, arg CreatePredictionJobParams) (PredictionJob, error)
	// Call only after LockForecastVersionsForActivation in the switch transaction.
	DeactivateForecastVersions(ctx context.Context) error
	// Run during worker maintenance, including after lowering max_attempts in
	// configuration, so exhausted queued jobs cannot occupy capacity forever.
	FailExhaustedQueuedPredictionJobs(ctx context.Context, arg FailExhaustedQueuedPredictionJobsParams) ([]FailExhaustedQueuedPredictionJobsRow, error)
	// A stale worker cannot requeue/fail a newer attempt or revive an expired lease.
	// retryable=false is terminal. A retry also requires remaining attempts.
	FinishPredictionJobWithError(ctx context.Context, arg FinishPredictionJobWithErrorParams) (PredictionJob, error)
	GetActiveForecastVersion(ctx context.Context) (ForecastVersion, error)
	GetForecastVersion(ctx context.Context, id pgtype.UUID) (ForecastVersion, error)
	GetPredictionJob(ctx context.Context, id pgtype.UUID) (PredictionJob, error)
	GetPredictionJobByRouteAndVersion(ctx context.Context, arg GetPredictionJobByRouteAndVersionParams) (PredictionJob, error)
	// Go converts validated, hour-aligned bounds to Europe/Moscow date/hour pairs.
	// The interval is [from, to); verify the exact hourly grid, not just its size.
	ListValidationPredictions(ctx context.Context, arg ListValidationPredictionsParams) ([]ValidationPrediction, error)
	// Use a short READ COMMITTED transaction: lock, GetForecastVersion (rollback if
	// missing), DeactivateForecastVersions, ActivateForecastVersion, commit.
	// The table lock serializes switches even when there is no active version yet.
	// All activation queries must use the same transaction; readers are not blocked.
	LockForecastVersionsForActivation(ctx context.Context) error
	// Short READ COMMITTED transaction, BEFORE taking any row locks:
	// lock -> GetPredictionJobByRouteAndVersion -> CountPendingPredictionJobs
	// -> CreatePredictionJob if below capacity -> commit. Reuse existing jobs even
	// at capacity. The lock serializes admissions; never keep it during an RPC.
	LockPredictionJobAdmission(ctx context.Context) error
	// Must run in the SAME transaction as CopyValidationPredictions and
	// CompletePredictionJob. No row means ownership was lost: ROLLBACK.
	// Check the exact response grid and metadata before opening the transaction.
	LockPredictionJobForPublication(ctx context.Context, arg LockPredictionJobForPublicationParams) (LockPredictionJobForPublicationRow, error)
	// Bounded recovery; SKIP LOCKED leaves jobs being published/renewed alone.
	// The next claim, not recovery, increments attempt_count.
	RecoverExpiredPredictionJobs(ctx context.Context, arg RecoverExpiredPredictionJobsParams) ([]RecoverExpiredPredictionJobsRow, error)
	// Materialization ensures ownership is checked against the locked row and the
	// actual clock AFTER waiting for that lock, not transaction-start time.
	// Zero affected rows means ownership was lost (or lease_seconds was invalid).
	RenewPredictionJobLease(ctx context.Context, arg RenewPredictionJobLeaseParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
