// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package forecasts_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateForecastVersion = `-- name: ActivateForecastVersion :one
UPDATE forecast_versions
SET is_active = true
WHERE id = $1::uuid
RETURNING
    id,
    model_version,
    dataset_version,
    history_end,
    forecast_from,
    forecast_to,
    timezone,
    is_active,
    created_at
`

// Call after deactivation in the same transaction. Roll back on any error.
func (q *Queries) ActivateForecastVersion(ctx context.Context, id pgtype.UUID) (ForecastVersion, error) {
	row := q.db.QueryRow(ctx, activateForecastVersion, id)
	var i ForecastVersion
	err := row.Scan(
		&i.ID,
		&i.ModelVersion,
		&i.DatasetVersion,
		&i.HistoryEnd,
		&i.ForecastFrom,
		&i.ForecastTo,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createForecastVersion = `-- name: CreateForecastVersion :one
INSERT INTO forecast_versions (
    id,
    model_version,
    dataset_version,
    history_end,
    forecast_from,
    forecast_to
) VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::timestamptz,
    $5::timestamptz,
    $6::timestamptz
)
RETURNING
    id,
    model_version,
    dataset_version,
    history_end,
    forecast_from,
    forecast_to,
    timezone,
    is_active,
    created_at
`

type CreateForecastVersionParams struct {
	ID             pgtype.UUID        `json:"id"`
	ModelVersion   string             `json:"model_version"`
	DatasetVersion string             `json:"dataset_version"`
	HistoryEnd     pgtype.Timestamptz `json:"history_end"`
	ForecastFrom   pgtype.Timestamptz `json:"forecast_from"`
	ForecastTo     pgtype.Timestamptz `json:"forecast_to"`
}

// Versions are registered inactive. Metadata is immutable after creation.
func (q *Queries) CreateForecastVersion(ctx context.Context, arg CreateForecastVersionParams) (ForecastVersion, error) {
	row := q.db.QueryRow(ctx, createForecastVersion,
		arg.ID,
		arg.ModelVersion,
		arg.DatasetVersion,
		arg.HistoryEnd,
		arg.ForecastFrom,
		arg.ForecastTo,
	)
	var i ForecastVersion
	err := row.Scan(
		&i.ID,
		&i.ModelVersion,
		&i.DatasetVersion,
		&i.HistoryEnd,
		&i.ForecastFrom,
		&i.ForecastTo,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateForecastVersions = `-- name: DeactivateForecastVersions :exec
UPDATE forecast_versions
SET is_active = false
WHERE is_active = true
`

// Call only after LockForecastVersionsForActivation in the switch transaction.
func (q *Queries) DeactivateForecastVersions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateForecastVersions)
	return err
}

const getActiveForecastVersion = `-- name: GetActiveForecastVersion :one
SELECT
    id,
    model_version,
    dataset_version,
    history_end,
    forecast_from,
    forecast_to,
    timezone,
    is_active,
    created_at
FROM forecast_versions
WHERE is_active = true
`

func (q *Queries) GetActiveForecastVersion(ctx context.Context) (ForecastVersion, error) {
	row := q.db.QueryRow(ctx, getActiveForecastVersion)
	var i ForecastVersion
	err := row.Scan(
		&i.ID,
		&i.ModelVersion,
		&i.DatasetVersion,
		&i.HistoryEnd,
		&i.ForecastFrom,
		&i.ForecastTo,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getForecastVersion = `-- name: GetForecastVersion :one
SELECT
    id,
    model_version,
    dataset_version,
    history_end,
    forecast_from,
    forecast_to,
    timezone,
    is_active,
    created_at
FROM forecast_versions
WHERE id = $1::uuid
`

func (q *Queries) GetForecastVersion(ctx context.Context, id pgtype.UUID) (ForecastVersion, error) {
	row := q.db.QueryRow(ctx, getForecastVersion, id)
	var i ForecastVersion
	err := row.Scan(
		&i.ID,
		&i.ModelVersion,
		&i.DatasetVersion,
		&i.HistoryEnd,
		&i.ForecastFrom,
		&i.ForecastTo,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const lockForecastVersionsForActivation = `-- name: LockForecastVersionsForActivation :exec
LOCK TABLE forecast_versions IN SHARE ROW EXCLUSIVE MODE
`

// Use a short READ COMMITTED transaction: lock, GetForecastVersion (rollback if
// missing), DeactivateForecastVersions, ActivateForecastVersion, commit.
// The table lock serializes switches even when there is no active version yet.
// All activation queries must use the same transaction; readers are not blocked.
func (q *Queries) LockForecastVersionsForActivation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockForecastVersionsForActivation)
	return err
}
