// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stops_sqlc

type Stop struct {
	ID           int64   `json:"id"`
	SourceStopID string  `json:"source_stop_id"`
	Name         string  `json:"name"`
	Latitude     float64 `json:"latitude"`
	Longitude    float64 `json:"longitude"`
}
