// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stops_sqlc

import (
	"context"
)

type Querier interface {
	GetStopByID(ctx context.Context, stopID int64) (Stop, error)
	GetStopBySourceID(ctx context.Context, sourceStopID string) (Stop, error)
	ListStops(ctx context.Context) ([]Stop, error)
	UpsertStop(ctx context.Context, arg UpsertStopParams) (Stop, error)
}

var _ Querier = (*Queries)(nil)
