// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stops.sql

package stops_sqlc

import (
	"context"
)

const getStopByID = `-- name: GetStopByID :one
SELECT id, source_stop_id, name, latitude, longitude
FROM stops
WHERE id = $1
`

func (q *Queries) GetStopByID(ctx context.Context, stopID int64) (Stop, error) {
	row := q.db.QueryRow(ctx, getStopByID, stopID)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.SourceStopID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getStopBySourceID = `-- name: GetStopBySourceID :one
SELECT id, source_stop_id, name, latitude, longitude
FROM stops
WHERE source_stop_id = $1
`

func (q *Queries) GetStopBySourceID(ctx context.Context, sourceStopID string) (Stop, error) {
	row := q.db.QueryRow(ctx, getStopBySourceID, sourceStopID)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.SourceStopID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listStops = `-- name: ListStops :many
SELECT id, source_stop_id, name, latitude, longitude
FROM stops
ORDER BY id
`

func (q *Queries) ListStops(ctx context.Context) ([]Stop, error) {
	rows, err := q.db.Query(ctx, listStops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stop{}
	for rows.Next() {
		var i Stop
		if err := rows.Scan(
			&i.ID,
			&i.SourceStopID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStop = `-- name: UpsertStop :one
INSERT INTO stops (source_stop_id, name, latitude, longitude)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (source_stop_id) DO UPDATE
SET name = EXCLUDED.name,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude
RETURNING id, source_stop_id, name, latitude, longitude
`

type UpsertStopParams struct {
	SourceStopID string  `json:"source_stop_id"`
	Name         string  `json:"name"`
	Latitude     float64 `json:"latitude"`
	Longitude    float64 `json:"longitude"`
}

func (q *Queries) UpsertStop(ctx context.Context, arg UpsertStopParams) (Stop, error) {
	row := q.db.QueryRow(ctx, upsertStop,
		arg.SourceStopID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
	)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.SourceStopID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
